{
   "version":"0.4",
   "title":"Contact us",
   "type":"page",
   "content":[
      {
         "id":"1bf58f2c",
         "settings":{
            "content_width":{
               "unit":"px",
               "size":1600,
               "sizes":[
                  
               ]
            }
         },
         "elements":[
            {
               "id":"496e71ed",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"f91c1ca",
                     "settings":{
                        "skin":"cover",
                        "title":"Contact us",
                        "description":"",
                        "button":"",
                        "min-height":{
                           "unit":"px",
                           "size":510,
                           "sizes":[
                              
                           ]
                        },
                        "__globals__":{
                           "title_color":""
                        },
                        "bg_image":{
                           "url":"http:\/\/ceit-ssc.ir\/wp-content\/uploads\/2021\/03\/Contact-Us-Background-copy.jpg",
                           "id":7066
                        },
                        "title_typography_typography":"custom",
                        "title_typography_font_family":"IranSansWeb",
                        "title_typography_font_size":{
                           "unit":"px",
                           "size":80,
                           "sizes":[
                              
                           ]
                        },
                        "title_typography_font_weight":"200",
                        "title_color":"#FFFFFF"
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"call-to-action",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      },
      {
         "id":"36e3bed2",
         "settings":[
            
         ],
         "elements":[
            {
               "id":"17426786",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"6b64b4c0",
                     "settings":{
                        "space":{
                           "unit":"px",
                           "size":46,
                           "sizes":[
                              
                           ]
                        }
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"spacer",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      },
      {
         "id":"46c2ee43",
         "settings":[
            
         ],
         "elements":[
            {
               "id":"7a6f2f6",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"7c33ee47",
                     "settings":{
                        "width":{
                           "unit":"%",
                           "size":73,
                           "sizes":[
                              
                           ]
                        },
                        "align":"center",
                        "look":"line_icon",
                        "text":"\u062c\u062f\u0627\u06a9\u0646\u0646\u062f\u0647",
                        "icon":{
                           "value":"fas fa-phone",
                           "library":"fa-solid"
                        },
                        "weight":{
                           "unit":"px",
                           "size":1.600000000000000088817841970012523233890533447265625,
                           "sizes":[
                              
                           ]
                        },
                        "primary_color":"#B0BDCE",
                        "__globals__":{
                           "color":"globals\/colors?id=text"
                        }
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"divider",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      },
      {
         "id":"2c0ce3ff",
         "settings":{
            "structure":"30"
         },
         "elements":[
            {
               "id":"49ea66bd",
               "settings":{
                  "_column_size":33,
                  "_inline_size":39.296999999999997044142219237983226776123046875
               },
               "elements":[
                  {
                     "id":"6ae9430d",
                     "settings":[
                        
                     ],
                     "elements":[
                        {
                           "id":"63619f26",
                           "settings":{
                              "_column_size":100,
                              "_inline_size":null
                           },
                           "elements":[
                              {
                                 "id":"3234d61f",
                                 "settings":{
                                    "title":"Our Contact information",
                                    "size":"large",
                                    "header_size":"h5",
                                    "_padding":{
                                       "unit":"px",
                                       "top":"0",
                                       "right":"0",
                                       "bottom":"10",
                                       "left":"0",
                                       "isLinked":false
                                    },
                                    "_border_border":"solid",
                                    "_border_width":{
                                       "unit":"px",
                                       "top":"0",
                                       "right":"0",
                                       "bottom":"1",
                                       "left":"0",
                                       "isLinked":false
                                    },
                                    "_border_color":"#E2E2E2",
                                    "__globals__":{
                                       "title_color":"globals\/colors?id=text"
                                    }
                                 },
                                 "elements":[
                                    
                                 ],
                                 "isInner":false,
                                 "widgetType":"heading",
                                 "elType":"widget"
                              }
                           ],
                           "isInner":true,
                           "elType":"column"
                        }
                     ],
                     "isInner":true,
                     "elType":"section"
                  },
                  {
                     "id":"4b4becf0",
                     "settings":[
                        
                     ],
                     "elements":[
                        {
                           "id":"2ce23a88",
                           "settings":{
                              "_column_size":100,
                              "_inline_size":null
                           },
                           "elements":[
                              {
                                 "id":"6cf32995",
                                 "settings":{
                                    "padding":{
                                       "unit":"px",
                                       "top":"15",
                                       "right":"15",
                                       "bottom":"15",
                                       "left":"15",
                                       "isLinked":true
                                    }
                                 },
                                 "elements":[
                                    {
                                       "id":"1e5719ba",
                                       "settings":{
                                          "_column_size":100,
                                          "_inline_size":null
                                       },
                                       "elements":[
                                          {
                                             "id":"3b6fd630",
                                             "settings":{
                                                "icon_list":[
                                                   {
                                                      "text":"Email : ceit.ssc94@gmail.com",
                                                      "selected_icon":{
                                                         "value":"fas fa-mail-bulk",
                                                         "library":"fa-solid"
                                                      },
                                                      "_id":"42fe79d",
                                                      "link":{
                                                         "url":"ceit.ssc94@gmail.com",
                                                         "is_external":"",
                                                         "nofollow":"",
                                                         "custom_attributes":""
                                                      }
                                                   },
                                                   {
                                                      "text":"Telegram : @ceitssc ",
                                                      "selected_icon":{
                                                         "value":"fab fa-telegram",
                                                         "library":"fa-brands"
                                                      },
                                                      "_id":"0412dd1",
                                                      "link":{
                                                         "url":"https:\/\/t.me\/ceit_ssc",
                                                         "is_external":"",
                                                         "nofollow":"",
                                                         "custom_attributes":""
                                                      }
                                                   },
                                                   {
                                                      "text":"Computer engineering department, Amirkabir University of Tehran, Hafez street, Tehran, Iran",
                                                      "selected_icon":{
                                                         "value":"fas fa-city",
                                                         "library":"fa-solid"
                                                      },
                                                      "_id":"e5e7bf4"
                                                   }
                                                ],
                                                "space_between":{
                                                   "unit":"px",
                                                   "size":25,
                                                   "sizes":[
                                                      
                                                   ]
                                                },
                                                "divider":"yes",
                                                "divider_weight":{
                                                   "unit":"px",
                                                   "size":2,
                                                   "sizes":[
                                                      
                                                   ]
                                                },
                                                "divider_width":{
                                                   "unit":"%",
                                                   "size":88,
                                                   "sizes":[
                                                      
                                                   ]
                                                },
                                                "text_indent":{
                                                   "unit":"px",
                                                   "size":17,
                                                   "sizes":[
                                                      
                                                   ]
                                                },
                                                "_border_border":"solid",
                                                "_border_width":{
                                                   "unit":"px",
                                                   "top":"0",
                                                   "right":"0",
                                                   "bottom":"0",
                                                   "left":"0",
                                                   "isLinked":false
                                                },
                                                "_border_radius":{
                                                   "unit":"px",
                                                   "top":"0",
                                                   "right":"0",
                                                   "bottom":"2",
                                                   "left":"0",
                                                   "isLinked":false
                                                },
                                                "_padding":{
                                                   "unit":"px",
                                                   "top":"15",
                                                   "right":"15",
                                                   "bottom":"15",
                                                   "left":"15",
                                                   "isLinked":true
                                                }
                                             },
                                             "elements":[
                                                
                                             ],
                                             "isInner":false,
                                             "widgetType":"icon-list",
                                             "elType":"widget"
                                          }
                                       ],
                                       "isInner":true,
                                       "elType":"column"
                                    }
                                 ],
                                 "isInner":true,
                                 "elType":"section"
                              },
                              {
                                 "id":"6a4c9e3e",
                                 "settings":[
                                    
                                 ],
                                 "elements":[
                                    {
                                       "id":"7259b2bb",
                                       "settings":{
                                          "_column_size":100,
                                          "_inline_size":null
                                       },
                                       "elements":[
                                          {
                                             "id":"3fdea4b0",
                                             "settings":{
                                                "address":"Computer Engineering Department, District 6, Tehran, Tehran Province, Iran",
                                                "zoom":{
                                                   "unit":"px",
                                                   "size":17,
                                                   "sizes":[
                                                      
                                                   ]
                                                },
                                                "height":{
                                                   "unit":"px",
                                                   "size":460,
                                                   "sizes":[
                                                      
                                                   ]
                                                }
                                             },
                                             "elements":[
                                                
                                             ],
                                             "isInner":false,
                                             "widgetType":"google_maps",
                                             "elType":"widget"
                                          }
                                       ],
                                       "isInner":true,
                                       "elType":"column"
                                    }
                                 ],
                                 "isInner":true,
                                 "elType":"section"
                              }
                           ],
                           "isInner":true,
                           "elType":"column"
                        }
                     ],
                     "isInner":true,
                     "elType":"section"
                  }
               ],
               "isInner":false,
               "elType":"column"
            },
            {
               "id":"7d3e8c5f",
               "settings":{
                  "_column_size":33,
                  "_inline_size":5.01499999999999968025576890795491635799407958984375
               },
               "elements":[
                  {
                     "id":"12c4bb2b",
                     "settings":[
                        
                     ],
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"spacer",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            },
            {
               "id":"3e9bc01a",
               "settings":{
                  "_column_size":33,
                  "_inline_size":55.02000000000000312638803734444081783294677734375
               },
               "elements":[
                  {
                     "id":"2390507a",
                     "settings":[
                        
                     ],
                     "elements":[
                        {
                           "id":"6c5aba86",
                           "settings":{
                              "_column_size":100,
                              "_inline_size":null
                           },
                           "elements":[
                              {
                                 "id":"46b878b1",
                                 "settings":{
                                    "title":"Keep in touch with us",
                                    "size":"large",
                                    "header_size":"h5",
                                    "_padding":{
                                       "unit":"px",
                                       "top":"0",
                                       "right":"0",
                                       "bottom":"10",
                                       "left":"0",
                                       "isLinked":false
                                    },
                                    "_border_border":"solid",
                                    "_border_width":{
                                       "unit":"px",
                                       "top":"0",
                                       "right":"0",
                                       "bottom":"1",
                                       "left":"0",
                                       "isLinked":false
                                    },
                                    "_border_color":"#E2E2E2",
                                    "__globals__":{
                                       "title_color":"globals\/colors?id=text"
                                    }
                                 },
                                 "elements":[
                                    
                                 ],
                                 "isInner":false,
                                 "widgetType":"heading",
                                 "elType":"widget"
                              }
                           ],
                           "isInner":true,
                           "elType":"column"
                        }
                     ],
                     "isInner":true,
                     "elType":"section"
                  },
                  {
                     "id":"7462a0d",
                     "settings":[
                        
                     ],
                     "elements":[
                        {
                           "id":"595a6d2",
                           "settings":{
                              "_column_size":100,
                              "_inline_size":null
                           },
                           "elements":[
                              {
                                 "id":"9f8d30",
                                 "settings":{
                                    "html":"[contact-form-7 id=\"6782\" title=\"contact-us-form-en\"]"
                                 },
                                 "elements":[
                                    
                                 ],
                                 "isInner":false,
                                 "widgetType":"html",
                                 "elType":"widget"
                              }
                           ],
                           "isInner":true,
                           "elType":"column"
                        }
                     ],
                     "isInner":true,
                     "elType":"section"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      }
   ]
}