{
   "version":"0.4",
   "title":"Archive",
   "type":"page",
   "content":[
      {
         "id":"14d556dd",
         "settings":[
            
         ],
         "elements":[
            {
               "id":"63ec4a7b",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"12143755",
                     "settings":{
                        "skin":"cover",
                        "layout":"above",
                        "bg_image":{
                           "url":"http:\/\/ceit-ssc.ir\/wp-content\/uploads\/2021\/03\/20190511_125242-copy-669x272-1.jpg",
                           "id":6946
                        },
                        "bg_image_size":"blog-single-1",
                        "title":"Faculty of Computer, Amirkabir University of Technology",
                        "description":"",
                        "title_tag":"span",
                        "button":"",
                        "link_click":"box",
                        "ribbon_title":"Amir Kabir",
                        "min-height":{
                           "unit":"px",
                           "size":550,
                           "sizes":[
                              
                           ]
                        },
                        "title_typography_typography":"custom",
                        "title_typography_font_family":"IranSansWeb",
                        "title_typography_font_size":{
                           "unit":"px",
                           "size":55,
                           "sizes":[
                              
                           ]
                        },
                        "title_typography_font_weight":"200",
                        "title_typography_text_decoration":"none",
                        "_margin":{
                           "unit":"px",
                           "top":"0",
                           "right":"0",
                           "bottom":"50",
                           "left":"0",
                           "isLinked":false
                        },
                        "__dynamic__":{
                           "link":"[elementor-tag id=\"496d701\" name=\"site-url\" settings=\"%7B%7D\"]"
                        },
                        "__globals__":{
                           "title_color":"globals\/colors?id=primary",
                           "ribbon_bg_color":"globals\/colors?id=primary"
                        }
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"call-to-action",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      },
      {
         "id":"79e6e5b",
         "settings":[
            
         ],
         "elements":[
            {
               "id":"5c8f18d4",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"40c5ce3a",
                     "settings":{
                        "skin":"minimal",
                        "placeholder":"Search ...",
                        "button_text":"Search",
                        "icon_size_minimal":{
                           "unit":"px",
                           "size":20,
                           "sizes":[
                              
                           ]
                        },
                        "input_border_color":"#B7B7B7",
                        "input_text_color_focus":"#FFFFFF",
                        "input_background_color_focus":"#5A5A5A",
                        "button_border_width":{
                           "unit":"px",
                           "top":"1",
                           "right":"1",
                           "bottom":"1",
                           "left":"1",
                           "isLinked":true
                        },
                        "border_radius":{
                           "unit":"px",
                           "size":10,
                           "sizes":[
                              
                           ]
                        }
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"search-form",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      },
      {
         "id":"6dc2e7fb",
         "settings":[
            
         ],
         "elements":[
            {
               "id":"28229c80",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"5ce85763",
                     "settings":{
                        "sitemap_items":[
                           {
                              "sitemap_title":"Our posts archive",
                              "_id":"35b47ba",
                              "sitemap_source_post_type":"post",
                              "sitemap_hierarchical":"",
                              "sitemap_depth":"4"
                           }
                        ],
                        "sitemap_columns":"1",
                        "sitemap_title_tag":"span",
                        "sitemap_add_nofollow":"yes",
                        "sitemap_exclude":[
                           
                        ],
                        "sitemap_list_indent":{
                           "unit":"px",
                           "size":25,
                           "sizes":[
                              
                           ]
                        },
                        "sitemap_section_padding":{
                           "unit":"px",
                           "top":"20",
                           "right":"20",
                           "bottom":"20",
                           "left":"20",
                           "isLinked":true
                        },
                        "sitemap_title_typography_typography":"custom",
                        "sitemap_title_typography_font_family":"IranSansWeb",
                        "sitemap_title_typography_font_size":{
                           "unit":"px",
                           "size":35,
                           "sizes":[
                              
                           ]
                        },
                        "sitemap_title_typography_font_weight":"200",
                        "sitemap_title_typography_line_height":{
                           "unit":"em",
                           "size":2.5,
                           "sizes":[
                              
                           ]
                        },
                        "sitemap_list_item_typography_typography":"custom",
                        "sitemap_list_item_typography_font_family":"IranSansWeb",
                        "sitemap_list_item_typography_font_size":{
                           "unit":"px",
                           "size":15,
                           "sizes":[
                              
                           ]
                        },
                        "sitemap_list_item_typography_font_weight":"200",
                        "sitemap_list_item_typography_line_height":{
                           "unit":"em",
                           "size":1.5,
                           "sizes":[
                              
                           ]
                        },
                        "sitemap_list_item_bullet_style":"circle"
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"sitemap",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      }
   ]
}