{
   "version":"0.4",
   "title":"\u064cWebsite header",
   "type":"header",
   "content":[
      {
         "id":"62f56f2c",
         "settings":{
            "background_background":"classic",
            "__globals__":{
               "background_color":"globals\/colors?id=primary"
            },
            "layout":"full_width",
            "content_width":{
               "unit":"px",
               "size":1600,
               "sizes":[
                  
               ]
            },
            "content_position":"middle",
            "overflow":"hidden"
         },
         "elements":[
            {
               "id":"205e85ce",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"4a593b2e",
                     "settings":{
                        "structure":"30"
                     },
                     "elements":[
                        {
                           "id":"75a782d8",
                           "settings":{
                              "_column_size":33,
                              "_inline_size":null
                           },
                           "elements":[
                              {
                                 "id":"6065e44",
                                 "settings":{
                                    "dropdown":"none",
                                    "__globals__":{
                                       "color_menu_item":"globals\/colors?id=secondary",
                                       "color_menu_item_hover":"globals\/colors?id=secondary",
                                       "pointer_color_menu_item_hover":"globals\/colors?id=secondary"
                                    }
                                 },
                                 "elements":[
                                    
                                 ],
                                 "isInner":false,
                                 "widgetType":"nav-menu",
                                 "elType":"widget"
                              }
                           ],
                           "isInner":true,
                           "elType":"column"
                        },
                        {
                           "id":"2ebdae24",
                           "settings":{
                              "_column_size":33,
                              "_inline_size":null
                           },
                           "elements":[
                              
                           ],
                           "isInner":true,
                           "elType":"column"
                        },
                        {
                           "id":"438d7fa4",
                           "settings":{
                              "_column_size":33,
                              "_inline_size":null
                           },
                           "elements":[
                              {
                                 "id":"3fde022f",
                                 "settings":{
                                    "social_icon_list":[
                                       {
                                          "_id":"9267967",
                                          "social_icon":{
                                             "value":"fab fa-telegram",
                                             "library":"fa-brands"
                                          },
                                          "item_icon_primary_color":"#8BCBE6",
                                          "item_icon_secondary_color":"#E0E0E0",
                                          "__globals__":{
                                             "item_icon_primary_color":""
                                          },
                                          "item_icon_color":"custom",
                                          "link":{
                                             "url":"https:\/\/t.me\/ceit_ssc",
                                             "is_external":"true",
                                             "nofollow":"",
                                             "custom_attributes":""
                                          }
                                       },
                                       {
                                          "_id":"9f2722f",
                                          "social_icon":{
                                             "value":"fab fa-twitter",
                                             "library":"fa-brands"
                                          },
                                          "item_icon_secondary_color":"#FFFFFF",
                                          "__globals__":{
                                             "item_icon_primary_color":"globals\/colors?id=primary"
                                          },
                                          "item_icon_color":"custom",
                                          "link":{
                                             "url":"https:\/\/twitter.com\/ceit_ssc",
                                             "is_external":"true",
                                             "nofollow":"",
                                             "custom_attributes":""
                                          }
                                       },
                                       {
                                          "_id":"8de2193",
                                          "social_icon":{
                                             "value":"fab fa-instagram",
                                             "library":"fa-brands"
                                          },
                                          "item_icon_color":"custom",
                                          "item_icon_secondary_color":"#F241E0",
                                          "__globals__":{
                                             "item_icon_primary_color":"globals\/colors?id=primary"
                                          },
                                          "link":{
                                             "url":"https:\/\/www.instagram.com\/accounts\/login\/?next=\/ceit_ssc\/",
                                             "is_external":"true",
                                             "nofollow":"",
                                             "custom_attributes":""
                                          }
                                       },
                                       {
                                          "_id":"a599a74",
                                          "social_icon":{
                                             "value":"fab fa-github",
                                             "library":"fa-brands"
                                          },
                                          "item_icon_color":"custom",
                                          "item_icon_secondary_color":"#000000",
                                          "__globals__":{
                                             "item_icon_primary_color":"globals\/colors?id=primary"
                                          },
                                          "link":{
                                             "url":"https:\/\/github.com\/AUT-CEIT-SSC",
                                             "is_external":"true",
                                             "nofollow":"",
                                             "custom_attributes":""
                                          }
                                       },
                                       {
                                          "_id":"977f726",
                                          "social_icon":{
                                             "value":{
                                                "url":"http:\/\/localhost:8080\/anjoman\/wp-content\/uploads\/2021\/01\/aparat-seeklogo.com_.svg",
                                                "id":106
                                             },
                                             "library":"svg"
                                          },
                                          "item_icon_color":"custom",
                                          "item_icon_secondary_color":"#FFFFFF",
                                          "__globals__":{
                                             "item_icon_primary_color":"globals\/colors?id=primary"
                                          },
                                          "link":{
                                             "url":"https:\/\/www.aparat.com\/ceit.ssc\/%D8%A7%D9%86%D8%AC%D9%85%D9%86_%D8%B9%D9%84%D9%85%DB%8C_%DA%A9%D8%A7%D9%85%D9%BE%DB%8C%D9%88%D8%AA%D8%B1",
                                             "is_external":"true",
                                             "nofollow":"",
                                             "custom_attributes":""
                                          }
                                       }
                                    ],
                                    "align":"left",
                                    "icon_size":{
                                       "unit":"px",
                                       "size":17,
                                       "sizes":[
                                          
                                       ]
                                    },
                                    "icon_padding":{
                                       "unit":"em",
                                       "size":0.5,
                                       "sizes":[
                                          
                                       ]
                                    },
                                    "hover_animation":"pop"
                                 },
                                 "elements":[
                                    
                                 ],
                                 "isInner":false,
                                 "widgetType":"social-icons",
                                 "elType":"widget"
                              }
                           ],
                           "isInner":true,
                           "elType":"column"
                        }
                     ],
                     "isInner":true,
                     "elType":"section"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      },
      {
         "id":"1f00724d",
         "settings":{
            "layout":"full_width",
            "content_width":{
               "unit":"px",
               "size":722,
               "sizes":[
                  
               ]
            },
            "_element_id":"top_navbar_menu",
            "background_background":"classic",
            "background_color":"#FFFFFF",
            "sticky":"top"
         },
         "elements":[
            {
               "id":"24b7d369",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"41f2f3fd",
                     "settings":{
                        "structure":"20"
                     },
                     "elements":[
                        {
                           "id":"5efd001",
                           "settings":{
                              "_column_size":50,
                              "_inline_size":13.034
                           },
                           "elements":[
                              {
                                 "id":"1278242e",
                                 "settings":{
                                    "image":{
                                       "url":"http:\/\/localhost:8080\/anjoman\/wp-content\/uploads\/2021\/01\/site-1.png",
                                       "id":111
                                    },
                                    "image_size":"medium_large",
                                    "image_custom_dimension":{
                                       "width":"12",
                                       "height":"10"
                                    },
                                    "link_to":"custom",
                                    "link":{
                                       "url":"http:\/\/localhost:8080\/anjoman\/",
                                       "is_external":"",
                                       "nofollow":"",
                                       "custom_attributes":""
                                    },
                                    "__dynamic__":{
                                       "link":"[elementor-tag id=\"b5ca3a2\" name=\"site-url\" settings=\"%7B%7D\"]"
                                    }
                                 },
                                 "elements":[
                                    
                                 ],
                                 "isInner":false,
                                 "widgetType":"image",
                                 "elType":"widget"
                              }
                           ],
                           "isInner":true,
                           "elType":"column"
                        },
                        {
                           "id":"25ae742f",
                           "settings":{
                              "_column_size":50,
                              "_inline_size":86.966
                           },
                           "elements":[
                              {
                                 "id":"6f595e76",
                                 "settings":{
                                    "indicator":"chevron",
                                    "__globals__":{
                                       "color_menu_item_hover":"globals\/colors?id=primary",
                                       "pointer_color_menu_item_hover":"globals\/colors?id=primary",
                                       "color_menu_item_active":"globals\/colors?id=primary",
                                       "pointer_color_menu_item_active":"globals\/colors?id=primary",
                                       "toggle_color":"",
                                       "toggle_background_color":"globals\/colors?id=primary",
                                       "toggle_background_color_hover":"",
                                       "background_color_dropdown_item_hover":"globals\/colors?id=primary",
                                       "dropdown_border_color":"globals\/colors?id=primary"
                                    },
                                    "animation_line":"drop-in",
                                    "full_width":"stretch",
                                    "menu_typography_typography":"custom",
                                    "menu_typography_font_family":"Roboto",
                                    "menu_typography_font_weight":"400",
                                    "menu_typography_text_decoration":"none",
                                    "color_menu_item_hover":"#6EC1E4",
                                    "pointer_color_menu_item_hover":"#6EC1E4",
                                    "color_menu_item_active":"#6EC1E4",
                                    "pointer_color_menu_item_active":"#6EC1E4",
                                    "dropdown_typography_typography":"custom",
                                    "dropdown_typography_font_family":"Roboto",
                                    "dropdown_typography_font_weight":"500",
                                    "dropdown_typography_text_decoration":"none",
                                    "padding_horizontal_dropdown_item":{
                                       "unit":"px",
                                       "size":20,
                                       "sizes":[
                                          
                                       ]
                                    },
                                    "padding_vertical_dropdown_item":{
                                       "unit":"px",
                                       "size":15,
                                       "sizes":[
                                          
                                       ]
                                    },
                                    "dropdown_divider_border":"solid",
                                    "dropdown_divider_color":"#E6E6E6",
                                    "dropdown_divider_width":{
                                       "unit":"px",
                                       "size":1,
                                       "sizes":[
                                          
                                       ]
                                    },
                                    "toggle_color":"#FFFFFF",
                                    "toggle_background_color":"#6EC1E4",
                                    "toggle_color_hover":"#F6F6F6",
                                    "toggle_background_color_hover":"#43A8D2",
                                    "menu_typography_font_size":{
                                       "unit":"px",
                                       "size":13,
                                       "sizes":[
                                          
                                       ]
                                    },
                                    "dropdown":"mobile",
                                    "dropdown_border_border":"solid",
                                    "dropdown_border_width":{
                                       "unit":"px",
                                       "top":"1",
                                       "right":"1",
                                       "bottom":"1",
                                       "left":"1",
                                       "isLinked":true
                                    }
                                 },
                                 "elements":[
                                    
                                 ],
                                 "isInner":false,
                                 "widgetType":"nav-menu",
                                 "elType":"widget"
                              }
                           ],
                           "isInner":true,
                           "elType":"column"
                        }
                     ],
                     "isInner":true,
                     "elType":"section"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      }
   ]
}