{
   "version":"0.4",
   "title":"\u064fSinglePage",
   "type":"single-page",
   "content":[
      {
         "id":"488e7b31",
         "settings":[
            
         ],
         "elements":[
            {
               "id":"4dbfd974",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"21db0c53",
                     "settings":{
                        "__dynamic__":{
                           "image":"[elementor-tag id=\"\" name=\"post-featured-image\" settings=\"%7B%22fallback%22%3A%7B%22url%22%3A%22%22%2C%22id%22%3A%22%22%7D%7D\"]"
                        }
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"theme-post-featured-image",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      },
      {
         "id":"44b82baf",
         "settings":[
            
         ],
         "elements":[
            {
               "id":"516dca7c",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"376f8a49",
                     "settings":{
                        "title":"\u0645\u062a\u0646 \u0633\u0631\u0628\u0631\u06af \u0631\u0648 \u0628\u0632\u0646 !"
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"heading",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      },
      {
         "id":"77740426",
         "settings":[
            
         ],
         "elements":[
            {
               "id":"290b2e1e",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"658c0153",
                     "settings":{
                        "editor":"<p>\u0645\u062d\u062a\u0648\u0627 \u0631\u0648 \u0628\u0631\u06cc\u0632 \u0627\u06cc\u0646\u062c\u0627 !<\/p>"
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"text-editor",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      },
      {
         "id":"5a10b6d6",
         "settings":[
            
         ],
         "elements":[
            {
               "id":"69688f57",
               "settings":{
                  "_column_size":100,
                  "_inline_size":null
               },
               "elements":[
                  {
                     "id":"3aa555d9",
                     "settings":{
                        "_skin":"theme_comments"
                     },
                     "elements":[
                        
                     ],
                     "isInner":false,
                     "widgetType":"post-comments",
                     "elType":"widget"
                  }
               ],
               "isInner":false,
               "elType":"column"
            }
         ],
         "isInner":false,
         "elType":"section"
      }
   ]
}